{application, jukebox,
 [{description, "Jukebox"},
  {id, "Jukebox"},
  {vsn, "1.0.0"},
  {modules, [configsession,
	     execdaemon,
	     history,
	     jukebox,
	     jukeboxsession,
	     jukebox_supervisor,
	     player,
	     spider,
	     tqueue,
	     trackdb,
	     volume]},
  {registered, [jukebox_supervisor,
		ibrowse,
		trackdb,
		player,
		volume]},
  {applications, [kernel, stdlib]},
  {mod, {jukebox, []}},
  {env, []}]}.
